version: "3.8"
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # Add any other required environment variables
    restart: unless-stopped
    # Add volumes if needed
    # volumes:
    #   - ./data:/app/data
